version: 2

jobs:
  Apollo Server:
    docker:
      - image: circleci/node:12.19

    steps:
      - checkout

#      - run: cd server && sudo npm i -g jest
#      - run: cd server && npm test --coverage

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install      
      
      # deploy app            
      - run:
          name: Deploy application 
          command: sls deploy -v --region $AWS_DEFAULT_REGION

      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}

workflows:
  version: 2
  Build and Test:
    jobs:
      - Apollo Server
